---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: document
  path: index.md
  label: Főoldal
- type: document
  path: tortenet.md
  label: Templomunk története
- type: document
  path: betlehem.md
  label: Betlehem
- type: document
  path: miserend.md
  label: Miserend
- type: document
  path: nyitvatartas.md
  label: Hivatal nyitvatartása
- type: document
  path: baratok.md
  label: Barátok lapja
- type: document
  path: hirdeteseink.md
  label: Hirdetéseink
- type: document
  path: hittan.md
  label: Hittan
upload_dir: assets/pdfs
public_path: "/assets/pdfs"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
